# Generated by Django 5.2.7 on 2025-10-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Imageltem",
            new_name="ImageItem",
        ),
    ]
